### ISSUE TITLE
http:<pod-ip>:8000/API/healthz is not connecting; connection refused

### ISSUE THREAD

**Issue by ananragha** [abcdesktopio/conf#6]
We have been testing abcdesktop in our microk8s environment for sometime now. Initially, about 2 months back, when this was the only service on the microk8s cluster, it used to work. Then we created different namespaces and enabled many of our services. Post some UI customization, when we tried to redeploy abcdesktop, pyod-od started throwing error - "http://10.1.230.63:8000/API/healthz": dial tcp 10.1.230.63:8000: connect: connection refused" and when we try to login, we are getting Gateway Timeout. Even anonymous user is not going through. 
What could be the reason?
Just for your information, we have enabled "dashboard-metrics-scraper" service and it is hosted in "kube-system" namespace and is using port 8000. Ideally it should not create any issues for pyod-od, but we are unable to get through.
Your guidance is highly appreciated. 
Best regards,
Raghav

**Comment by alexandredevely** [comment]
Hello Raghav,

Thank you for you message. 

It seems that pyos pod doesn't start.
Could you read pyos logs ?
dashboard-metrics-scraper should not create any issues for pyod-od. I agree with you. 

Could update to release 3.1 ( I suppose that this issue come from release 2.0 )
- delete abcdesktop namespace
- create a new directory ( to prevent file sharing from 2.0 to 3.1), and go to this directory
- install 3.1 using this page https://www.abcdesktop.io/3.1/setup/kubernetes_abcdesktop/

Thank you for your feedback

Alexandre

**Comment by ananragha** [comment]
[logs-from-pyos-in-pyos-od-6cbc8cf6f-qnw67.log](https://github.com/abcdesktopio/conf/files/13611290/logs-from-pyos-in-pyos-od-6cbc8cf6f-qnw67.log)
Hello Alexandre,
As you suggested, I have installed the version 3.1 and I have done the installation using the install.sh script with a different namespace. I observed that pyos-od pod takes a long time to come live. It restarts about 4 - 5 times and till then, the script keeps waiting. Initially I thought it is resource issue and I added two more nodes to the cluster to ensure that we have sufficient resources. But the same issue continues.  
Once the pyos-od comes up, if we try to login using our public ip - http://<public-ip>:30443 - the login screen comes up. But if we start any user session, either anonymous or otherwise, we can see the session related logs in pyos-od pod, but front-en throws "Gateway Timeout" error and user session does not load. 
As you suggested, we removed the old workspace, created a separate work space, installed the platform using command "./install-3.1.sh --namespace secureworkspace". Issue we are facing are detailed above. 
I am attaching the od.config file with this as well. 
Look forward for your guidance to get this up & running. 

Best regards,
Raghav 

[od.config.txt](https://github.com/abcdesktopio/conf/files/13611577/od.config.txt)

**Comment by alexandredevely** [comment]
Hi Raghav,

Thank you for you logs file and for your od.config file.
Your od.config is correct. 
Pyos does auth for user `fry` and them nothing, no more line in the log file. Pyos doesn't create the pod desktop, and the most important point, pyos doesn't receive any `launchdesktop` http request, this is stange.

What pyos should do 
- auth user
- create pod for user

It seems that pyos dies after auth or don't receive the `launchdesktop` http request. 

- Do you use ARM64 or AMD64 processor ?
- Do you add an ingress controller ?
- Do you read some events with command `kubectl get events -n abcdesktop` ?
- Could you upgrade the resources limits and probe (or remove both of them for troubleshooting ) in the pyos deployment description ?

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: abcdesktop
  name: pyos-od
  labels:
    abcdesktop/role: pyos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pyos-od
  template:
    metadata:
      namespace: abcdesktop
      labels:
        name: pyos-od
        run: pyos-od
        netpol/https: 'true'
        netpol/ldaps: 'true'
        netpol/auth: 'true'
        netpol/cifs: 'true'
        netpol/api: 'true'
        netpol/dns: 'true'
        netpol/mongodb: 'true'
        netpol/memcached: 'true'
        netpol/graylog: 'true'
    spec:
      serviceAccountName: pyos-serviceaccount
      containers:
      - name : pyos
        imagePullPolicy: Always
        image: abcdesktopio/oc.pyos:3.1
        command:
            - "/var/pyos/od.py"
        volumeMounts:
          - name: jwtsigningkeys
            mountPath: "/config.signing"
            readOnly: true
          - name: jwtusersigningkeys
            mountPath: "/config.usersigning"
            readOnly: true
          - name: jwtpayloadkeys
            mountPath: "/config.payload"
            readOnly: true
          - name: volume-abcdesktop-config
            mountPath: /var/pyos/od.config
            subPath: od.config
            readOnly: true
        ports:
          - containerPort: 8000
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: secret-mongodb
                key: MONGODB_URL
      volumes:
        - name: jwtusersigningkeys
          secret:
            secretName: abcdesktopjwtusersigning
        - name: jwtsigningkeys
          secret:
            secretName: abcdesktopjwtdesktopsigning
        - name: jwtpayloadkeys
          secret:
            secretName: abcdesktopjwtdesktoppayload
        - name: volume-abcdesktop-config
          configMap:
            name: abcdesktop-config
      dnsPolicy: ClusterFirst
---
```


If you can't get more details, can you look at the front web browser

The web browser must call `API/composer/launchdesktop`


The payload is a json 

```json
{
  "width": 1440,
  "height": 821,
  "hostname": "<YOUR WEB SITE HERE>",
  "timezone": "Europe/Paris"
}
```

and you gets a json when the user's pod starts 

```json
{
  "status": 200,
  "result": {
    "target_ip": "<YOUR WEB SITE HERE>",
    "vncpassword": "lOsXRY0IGgW5JWU",
    "authorization": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJrZXkiOjAsIm5mYiI6MTcwMjA0OTA1MiwiaGFzaCI6IlA1Z2RHSVlGWmhLWnZRbGFkV28vYkFSNFBCcXF4dkE2aEJkbE1LcDdZSVhLbEhHNEZ4Y0lqc05wdXZDNExSZVpCWHE3b2JiRXpTSW5uQTBDVC9vbFVaMHNhM3pGRVBjYzdVSGh1ckxEZFp4c1Y2c1pEUkhnWjVlampnbHgvRHk5UHFXTlFXQVFOS1Rna1M4a0VKNmtJTTZaZjBPZGZleWhSaUJjaXRoNG9IRT0iLCJleHAiOjE3MDIwNjM0NTJ9.Fe0LAopOTMvmd1Lq1xlVYFrh7ZqLXzfUQHSByzU7Kz22KU3WxAEF8tbvrwkkaPlNnSP_o2RQp03TtY-Ro_s0ERD2OWe37WFUpR4LKs2oT6ZGCKYgxzZHxaW-Az61Dpga3dlo29CmZqu5b4TiiEnIabfdG6oXdo2Y-EaevWm6-Tk",
    "websocketrouting": "http_origin",
    "websockettcpport": 6081,
    "expire_in": 14400
  },
  "message": "ok"
}
```

Look at [https://demo.abcdesktop.io](https://demo.abcdesktop.io) to compare your results.


- Could you give me more detail about "dashboard-metrics-scraper" service.

I want to deploying the Dashboard UI as you've done.
To deploy it, you just run the following command:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
```

Thank you Raghav
See you

Alexandre

**Comment by ananragha** [comment]
Hello Alexandre,
A bit more information about our setup. 
1. We use AMD64 servers, totally 7 of them. Each with 2 vCPU and 16 GB memory, 128 GB SSD primary drives. The user data is stored on a NFS server with over 10 TB of storage. 
2. The base OS is Ubuntu 22.04 with microk8s, one of the VM is acting as master and 6 of the worker nodes. Each VM has 5 Gbps NIC and all of them are in the same Subnet.
3. All our server are in Colocated Data Center and hence we access the UI through the public IP. At the moment, we do not have an **Ingress Controller**. But we have plan to configure one once this goes live and our tests are complete. 

More about "dashboard-metrics-scrapper"  service:
It is small binary which polls the nodes, pods, and cluster for metrics every one minute. This service gets enabled as soon as you enable metrics-server. The Health Check URI is http://[host]:8000/. You may find more details about it at the below link. 

https://github.com/kubernetes/dashboard/tree/master/modules/metrics-scraper

It appears, this is intervening in the abcdesktop operations. pyos-od may not be able to get a lock on port 8000. 

We probably have to change the pyos-od port in all configurations - od.config, abcdesktop.yaml and other applicable configuration files and check, if this is the root cause. 

As you suggested, I will remove the resource limits, disable health check probes and check and revert back to you. 

Best regards,
Raghav

**Comment by ananragha** [comment]
Additionally, I must inform you that this k8s setup has 8 namespaces and primary one is "wtitc", which houses our product Ndryve (https://dryve.wtitc.org). None of the service here uses port 8000.

**Comment by ananragha** [comment]
Hi,

I tried changing the port from 8000 to 8001 but the same result. Authentication is going through. I can see that Authentication is getting completed in less than 1 second. But Frontend is not receiving that confirmation from back end within the stipulated time and it is timing out. 
I also observed, from the logs that there is a gap of over 7 minutes in the different entries and authentication process completion, and by then front end is timing out. 
I have attached the logs once again for your reference. 
[logs-from-pyos-in-pyos-od-55cbc68f55-x5fpf.log](https://github.com/abcdesktopio/conf/files/13619688/logs-from-pyos-in-pyos-od-55cbc68f55-x5fpf.log)
Also, from the frontend, it is observed, frontend is calling /API/auth/auth, sending requests, waiting for one minute and at this point it is receiving the Gateway Timeout. 
I have attached screenshots from frontend. 
Hope this is useful. 
![Screenshot from 2023-12-09 00-00-53](https://github.com/abcdesktopio/conf/assets/125240600/4bf240a0-1e3b-465f-8ffd-bd2be7c0a313)
![Screenshot from 2023-12-09 00-01-59](https://github.com/abcdesktopio/conf/assets/125240600/ce676b82-55aa-466e-9a77-08d1d5dc2d6c)
![Screenshot from 2023-12-09 00-03-13](https://github.com/abcdesktopio/conf/assets/125240600/115fbb11-6399-4f20-88d1-ec2236e883e3)
![Screenshot from 2023-12-09 00-00-21](https://github.com/abcdesktopio/conf/assets/125240600/c13cfdea-9362-4fd4-bf9a-d395a19e2853)
![Screenshot from 2023-12-09 00-01-23](https://github.com/abcdesktopio/conf/assets/125240600/8e4924f6-d529-4be3-bbb0-82a1c4015972)
![Screenshot from 2023-12-09 00-02-19](https://github.com/abcdesktopio/conf/assets/125240600/4dd6c1ef-3eee-488b-95c5-1e2e9c561c59)
![Screenshot from 2023-12-09 00-03-27](https://github.com/abcdesktopio/conf/assets/125240600/635423b4-ebe0-45d4-b98c-6a494defc459)
Now started wondering, do I create a separate cluster and deploy abcdesktop?
Best regards,
Raghav

**Comment by ananragha** [comment]
Hello Alexandre,

It now started working.

Basically, I created a fresh cluster, stopped short of enabling Kubernetes Dashboard, thus ensured that the port 8000 is free across cluster and, upon installation using install-3.1.sh script, with default settings, all services went up immediately and desktops are loading. 

It is now clear that the dashboard-metrics-scrapper service is interfering with pyos on port 8000, causing it to pause and thus time outs in front end. 

I also tried to change the pyos port from 8000 to 8001, changed the port in od.config, abcdesktop.yaml file (in nginx configuration, the container port and in service definition, still the problem persists. 

Probably this needs more testing with new ports, new workspace settings, which I will do and report back here. 

Hope this is fine. 

Best regards,
Raghav

**Comment by alexandredevely** [comment]
Hello Raghav,

Thank you so much for this troubleshooting guide, this is so great to read you.

I will install the same [metrics-scraper](https://github.com/kubernetes/dashboard/tree/master/modules/metrics-scraper) as you. 

About `pyos` and the TCP port 
- `pyos` use the default TCP port `8000`.

You can change it, but I don't understand why the tcp port 8000 is not free inside his own container.
The TCP port 8000 is local to the container in abcdesktop namespace and them to the forwarded by the kubernetes service port in abcdesktop namespace too.

To change and replace TCP port 8000 by another value

- Update the kubernetes deployment `- containerPort: 8000` and all `8000` values
- Update the kubernetes config map nginx-config `set $api_service_tcp_port 8000;`  
- Update the kubernetes service named pyos to use new TCP Port
- Update the kubernetes config map abcdesktop-config (source file od.config) `server.socket_port: 8000`

nginx pod acts as a reverse proxy and forward http request to API service (pyos)

In the routing table[route.conf](https://github.com/abcdesktopio/oc.nginx/blob/main/etc/nginx/route.conf) you can find the `proxy_pass` to reach `pyos`

```
location ~ ^/(moauth|fauth|gauth|oauth|autologin|API|status) {
                include		proxy.conf;
                proxy_pass      http://$my_proxy:$api_service_tcp_port;
		break;
        }
```

Only nginx service is defined as a `type: NodePort` by default . 
I use nodePort to make it simplest as possible but of course you can change it.

```
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: abcdesktop
  labels:
    abcdesktop/role: nginx
spec:
  type: NodePort
  selector:
    run: nginx-od
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30443
    targetPort: 80
    name: http
---
```


See you
Alexandre
